/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export class ExternalObject<T> {
  readonly '': {
    readonly '': unique symbol
    [K: symbol]: T
  }
}
export interface Entries {
  name: string
  files: Array<string>
}
export function getUnchangedEntries(cacheDir: string): Array<string>
export function cacheEntries(cacheDir: string, entries: Array<Entries>): Promise<unknown>
